### ISSUE TITLE
Roadmap to PlatziKey 3

### ISSUE THREAD

**Issue by 360macky** [360macky/platkey#1]
Some ideas/features/etc to include in the next version:

- [x] Remove innerHTML for textContent property
- [x] Integrate ARIA
- [x] Create a landing page
- [x] Correct errors with Ctrl and Shift pressed at the same time
- [x] Augmented search like Spotlight
- [x] New shortcuts for classes
- [x] New shortcuts for notes (aportes) creation
- [x] Support for Safari

**Comment by 360macky** [comment]
Removing light theme feature to follow Platzi style guidelines.

**Comment by 360macky** [comment]
Add "Integrate support in Safari" as another feature for the V3.

**Comment by 360macky** [comment]
Add "Support for Firefox" as another features for the V3m

**Comment by 360macky** [comment]
Now Safari support is completed!

**Comment by 360macky** [comment]
Also the landing page is completed! 😊

**Comment by 360macky** [comment]
Submitting to App Store 🚀🍎
