### ISSUE TITLE
Roadmap to PlatKey 4

### ISSUE THREAD

**Issue by 360macky** [360macky/platkey#8]
For 3.5
- [ ] Add src/ folder to enhance software structure
- [ ] i18n support for English, Spanish and Portuguese

For 4.0
- [ ] Add "Experimental Features" panel

Drop your ideas here! If you want more features for PlatKey Extension 😄

**Comment by 360macky** [comment]
I've been thinking about the i18n support. I could use:

- Custom PlatKey i18n Engine
- [Chrome i18n infrastructure](https://developer.chrome.com/docs/extensions/reference/i18n/)

**Comment by 360macky** [comment]
In order to have support for Webkit (and maybe in the future for Firefox), I'll use a custom engine for i18n.

**Comment by 360macky** [comment]
The management of files is quite complex at this point.

I'm opening #9.
